# Generated by Django 5.2.6 on 2025-09-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_id', models.CharField(max_length=50, unique=True)),
                ('encounter_type', models.CharField(blank=True, max_length=50, null=True)),
                ('service_date', models.DateField(blank=True, null=True)),
                ('national_id', models.CharField(max_length=50)),
                ('member_id', models.CharField(max_length=50)),
                ('facility_id', models.CharField(max_length=50)),
                ('unique_id', models.CharField(blank=True, max_length=50, null=True)),
                ('diagnosis_codes', models.TextField(blank=True, null=True)),
                ('service_code', models.CharField(max_length=50)),
                ('paid_amount_aed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('approval_number', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VALIDATED', 'Validated'), ('NOT_VALIDATED', 'Not Validated')], default='PENDING', max_length=20)),
                ('error_type', models.CharField(choices=[('NONE', 'No Error'), ('TECHNICAL', 'Technical Error'), ('MEDICAL', 'Medical Error'), ('BOTH', 'Both Errors')], default='NONE', max_length=20)),
                ('error_explanation', models.TextField(blank=True, null=True)),
                ('recommended_action', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rule_type', models.CharField(choices=[('TECHNICAL', 'Technical'), ('MEDICAL', 'Medical')], max_length=20)),
                ('tenant_id', models.CharField(default='default', max_length=50)),
                ('parsed_json', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
